{"name": "creation of past entries", "status": "broken", "statusDetails": {"message": "TypeError: pretty_format() missing 1 required positional argument: 'obj'\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\api\\async_step.py\", line 157, in wrapped_decorator\n    return step_decorator(astep_func, context, *args, **kwargs)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\api\\async_step.py\", line 124, in step_decorator\n    loop.run_until_complete(astep_func(context, *args, **kwargs))\n  File \"C:\\Users\\wsu\\anaconda3\\lib\\asyncio\\base_events.py\", line 616, in run_until_complete\n    return future.result()\n  File \"features\\steps\\reconciliation_upload.py\", line 84, in send_fees_riskbot\n    file.write(str(message.media.pretty_format())+'\\n')\n"}, "steps": [{"name": "Given telegram", "status": "broken", "statusDetails": {"message": "TypeError: pretty_format() missing 1 required positional argument: 'obj'\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\api\\async_step.py\", line 157, in wrapped_decorator\n    return step_decorator(astep_func, context, *args, **kwargs)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\api\\async_step.py\", line 124, in step_decorator\n    loop.run_until_complete(astep_func(context, *args, **kwargs))\n  File \"C:\\Users\\wsu\\anaconda3\\lib\\asyncio\\base_events.py\", line 616, in run_until_complete\n    return future.result()\n  File \"features\\steps\\reconciliation_upload.py\", line 84, in send_fees_riskbot\n    file.write(str(message.media.pretty_format())+'\\n')\n"}, "start": 1610380113633, "stop": 1610380120158}], "start": 1610380113632, "stop": 1610380120159, "uuid": "345fe579-6c26-41d6-9029-5182f7d7f16d", "historyId": "af8c3982c62583736161e6767ac3b793", "fullName": "features/reconciliation_upload.feature:creation of past entries", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "reconciliation upload"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}