{"name": "check reports update", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 102, in step_impl\n    assert answer in response.text\n"}, "steps": [{"name": "Given check status of \"reports update\": false", "status": "passed", "start": 1610724117172, "stop": 1610724117196}, {"name": "And activate upload from propreports", "status": "passed", "start": 1610724117196, "stop": 1610724117272}, {"name": "When pause - 10 sec(s)", "status": "passed", "start": 1610724117273, "stop": 1610724127273}, {"name": "Then check status of \"reports update\": true", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 102, in step_impl\n    assert answer in response.text\n"}, "start": 1610724127275, "stop": 1610724127305}], "start": 1610724117171, "stop": 1610724127306, "uuid": "7a3ce089-8531-448d-bfea-6fe28cd12d86", "historyId": "3f03cfe28a6a292071c86abc39e5a396", "fullName": "features/II-Reconciliation/II-reconciliation_risk.feature:check reports update", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "check all user_data"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}