{"name": "not authenticated user -- @1.13 cases", "status": "passed", "steps": [{"name": "Given alien makes get request: /reconciliation/status/", "status": "passed", "start": 1611333543661, "stop": 1611333543695}, {"name": "Then check response of request: Authentication credentials were not provided. is True", "status": "passed", "start": 1611333543696, "stop": 1611333543696}], "parameters": [{"name": "url", "value": "/reconciliation/status/"}, {"name": "method", "value": "get"}, {"name": "bool", "value": "True"}], "start": 1611333543660, "stop": 1611333543696, "uuid": "40db6afd-36f3-4582-83a7-6b2eefe4c98b", "historyId": "d3e18fdcfa3cf024468fb4788d7c344c", "fullName": "features/II-Reconciliation/III-reconciliation_access.feature:not authenticated user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "reconciliation check access"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}