{"name": "check all user_data", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 48, in step_impl\n    assert False\n"}, "steps": [{"name": "Given get all user_data", "status": "passed", "start": 1610716009040, "stop": 1610716009285}, {"name": "And get user_data from dataset", "status": "passed", "start": 1610716009286, "stop": 1610716009298}, {"name": "Then compare userdata lists", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_II.py\", line 48, in step_impl\n    assert False\n"}, "start": 1610716009300, "stop": 1610716009302}], "start": 1610716009039, "stop": 1610716009303, "uuid": "b5bc6202-7378-4cc0-82c9-dd2d2fcd1a26", "historyId": "2e25d35ecebb550a6fe920f010e434b9", "fullName": "features/II-Reconciliation/II-reconciliation_risk.feature:check all user_data", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "check all user_data"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}