{"name": "check /reconciliation/user_data/", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_I_upload.py\", line 160, in step_impl\n    assert context.ac_template==context.exp_template\n"}, "steps": [{"name": "Given create expected template of user_data", "status": "passed", "start": 1611569132236, "stop": 1611569132237}, {"name": "And get actual template of user_data", "status": "passed", "start": 1611569132237, "stop": 1611569132311}, {"name": "Then compare actual and expected templates", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\wsu\\pycharmprojects\\msw_api\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\reconciliation_I_upload.py\", line 160, in step_impl\n    assert context.ac_template==context.exp_template\n"}, "start": 1611569132312, "stop": 1611569132312}], "start": 1611569132235, "stop": 1611569132314, "uuid": "4492f054-73ff-41ad-8b68-9777668eb5db", "historyId": "a25d58092254c90c0631e0b574751eb3", "fullName": "features/II-Reconciliation/II-reconciliation_upload.feature:check /reconciliation/user_data/", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "manager_user"}, {"name": "tag", "value": "super_user"}, {"name": "feature", "value": "reconciliation upload"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}